@extends('sp_template')
@section('content')

    <div class="page-header  page-header_align_center" style="background-color:#f4f6fd; height:220px; margin-bottom:50px; padding-top:0px; padding-bottom:0px;"><div class="page-header_wrapper"><div class="wgl-container"><div class="page-header_content"><h1 class="page-header_title" style="color:#252525; font-size:42px; line-height:54px;">FAQ</h1><div class="page-header_breadcrumbs" style="color:#252525; font-size:16px; line-height:34px;"><div class="breadcrumbs"><a href="/" class="home">Home</a> <span class="divider"></span> <span class="current">FAQ</span></div><!-- .breadcrumbs --></div></div></div></div><div id="page-title-particles-js" class="particles-js" data-particles-type="hexagons" data-particles-number="30" data-particles-line="false" data-particles-size="5" data-particles-speed="2" data-particles-hover="false" data-particles-hover-mode="bubble" data-particles-colors-type="random_colors" data-particles-color="#ff7e00,#3224e9,#69e9f2"><canvas class="particles-js-canvas-el" width="1349" height="220" style="width: 100%; height: 100%;"></canvas></div></div>
    <main id="main"><div class="wgl-container">
            <div class="row">
                <div id="main-content" class="wgl_col-12">
                    <div style="z-index: 2; " class="vc_row wpb_row vc_row-fluid wgl-row-animation"><div class="wpb_column vc_column_container vc_col-sm-12 vc_col-md-7"><div class="vc_column-inner"><div class="wpb_wrapper"><div id="seofy_dbl_5dc8112704840" class="seofy_module_double_headings aleft"><div class="heading_title" style="font-size:36px; line-height:1.333; font-weight:800; "><span class="heading_divider"></span><div class="heading_title_mobile" style="font-size:33px; line-height: 1.333;"><div>Most Popular Questions</div></div></div></div>
                                    <div class="seofy_module_spacing"><div class="spacing_size spacing_size-initial" style="height:21px;"></div></div>
                                    <div class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right vc_toggle_active"><div class="vc_toggle_title"><h4>1. Why Choose Us?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>We have been in the internet marketing industry for a while now. Our parent company has been creating online monetizing solutions since 2008. We have grown our network to more than 730,000 members who have earned over $158,670,000.</p>
                                        </div></div><div class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>2. How Does This Work?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>We strive to provide straight transparency to our members. Money generated from ad-spend revenue and sponsorship products is used to pay our members. By inviting friends, you are building traffic to our site and increasing ad revenue. You are also increasing exposure to our sponsors’ products, ultimately, increasing sponsor relations across our network.</p>
                                        </div></div><div class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>3. How Do I Earn?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>Earning on Tap 2 Earn is simple. You can earn by inviting friends to our site. Referring isn’t for you? You can also earn by testing some of our sponsors’ products in the members’ area.</p>
                                        </div></div><div class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>4. How Do I Get Paid?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>When you are ready to get paid, simply request your payment in the members’ area. We pay our members through PayPal, Cash App, Bitcoin, and mailed checks. Don’t see a payment method that works for you? We will be adding more in the future!</p>
                                        </div></div><div class="vc_toggle vc_toggle_ vc_toggle_color_plus  vc_toggle_size_right"><div class="vc_toggle_title"><h4>7. How Long Does It Take To Get Paid?</h4><i class="vc_toggle_icon"></i></div><div class="vc_toggle_content"><p>Usually, payments are sent instantly when scheduled. However, in rare cases, some problems may arise.</p>
                                        </div></div><div id="seofy_spacer_5dc8112706ad0" class="seofy_module_spacing responsive_active"><div class="spacing_size spacing_size-initial" style="height:30px;"></div><div class="spacing_size spacing_size-desktops" style="height:60px;"></div></div>
                                </div></div></div><div class="wpb_column vc_column_container vc_col-sm-12"><div class="vc_column-inner"><div class="wpb_wrapper"><div id="seofy_spacer_5dc8112706eed" class="seofy_module_spacing responsive_active"><div class="spacing_size spacing_size-initial" style="height:70px;"></div><div class="spacing_size spacing_size-tablet" style="height:75px;"></div></div>
                                </div></div></div><div class="extended-parallax" data-paroller-type="foreground" style="top: 80%; left: 80%; transform: unset; transition: transform 0s linear 0s; will-change: transform;" data-paroller-direction="vertical" data-paroller-factor="0.2"><img src="/wp-content/uploads/2018/11/section_about_us_02.png" alt="" data-lazy-src="/wp-content/uploads/2018/11/section_about_us_02.png" class="lazyloaded" data-was-processed="true"><noscript><img src="/wp-content/uploads/2018/11/section_about_us_02.png" alt="" /></noscript></div><div class="extended-parallax" data-paroller-type="foreground" style="top: 102%; left: 98%; transform: unset; transition: transform 0s linear 0s; will-change: transform;" data-paroller-direction="vertical" data-paroller-factor="0.3"><img src="/wp-content/uploads/2018/11/Vector-Smart-Object-copy-24.png" alt="" data-lazy-src="/wp-content/uploads/2018/11/Vector-Smart-Object-copy-24.png" class="lazyloaded" data-was-processed="true"><noscript><img src="/wp-content/uploads/2018/11/Vector-Smart-Object-copy-24.png" alt="" /></noscript></div></div>
                </div>

            </div>
        </div>

    </main>

@endsection
@section('jscript')
    <script type="text/javascript">
    </script>
@endsection
