@extends('sp_template')
@section('content')

    <div class="page-header  page-header_align_center" style="background-color:#f4f6fd; height:220px; margin-bottom:50px; padding-top:0px; padding-bottom:0px;"><div class="page-header_wrapper"><div class="wgl-container"><div class="page-header_content"><h1 class="page-header_title" style="color:#252525; font-size:42px; line-height:54px;">Privacy Policy</h1><div class="page-header_breadcrumbs" style="color:#252525; font-size:16px; line-height:34px;"><div class="breadcrumbs"><a href="/" class="home">Home</a> <span class="divider"></span> <span class="current">Privacy Policy</span></div><!-- .breadcrumbs --></div></div></div></div><div id="page-title-particles-js" class="particles-js" data-particles-type="hexagons" data-particles-number="30" data-particles-line="false" data-particles-size="5" data-particles-speed="2" data-particles-hover="false" data-particles-hover-mode="bubble" data-particles-colors-type="random_colors" data-particles-color="#ff7e00,#3224e9,#69e9f2"><canvas class="particles-js-canvas-el" width="1349" height="220" style="width: 100%; height: 100%;"></canvas></div></div>

    <main id="main"><div class="wgl-container">
            <div class="row">
                <div id="main-content" class="wgl_col-12">
                    <div class="document-preview-layout-document-previewer-wrapper-e49798">
                        <div>
                            <div class="document-previewer-wrapper-04553d">
                                <div data-custom-class="body">
                                    <p><strong><span>PRIVACY POLICY&nbsp;&nbsp;&nbsp;</span>&nbsp;</strong></p>
                                    <p><span><strong>Last updated&nbsp;April 25, 2018&nbsp;</strong>&nbsp;</span></p>
                                    <p><span>Thank you for choosing to be part of our community at&nbsp;Survey Bounce&nbsp;(“<strong>Company</strong>”, “<strong>we</strong>”, “<strong>us</strong>”, or “<strong>our</strong>”). We are committed to protecting your personal information and your right to privacy. If you have any questions or concerns about our&nbsp;policy, or our practices with regards to your personal information, please contact us at&nbsp;official@surveybounce.com.&nbsp;</span></p>
                                    <p><span>When you visit our&nbsp;website&nbsp;,&nbsp;and use our services, you trust us with your personal information. We take your privacy very seriously. In this&nbsp;privacy policy, we seek to explain to you in the clearest way possible what information we collect, how we use it and what rights you have in relation to it. We hope you take some time to read through it carefully, as it is important. If there are any terms in this&nbsp;privacy policy&nbsp;that you do not agree with, please discontinue use of our&nbsp;Sites&nbsp;and our services.&nbsp;</span></p>
                                    <p><span>This&nbsp;privacy policy&nbsp;applies to all information collected through our&nbsp;website&nbsp;(such as&nbsp;),&nbsp;and/or any related services, sales, marketing or events (we refer to them collectively in this&nbsp;privacy policy&nbsp;as the “<strong>Services</strong>“).&nbsp;&nbsp;</span></p>
                                    <p><span><strong>Please read this&nbsp;privacy policy&nbsp;carefully as it will help you make informed decisions about sharing your personal information with us.&nbsp;&nbsp;</strong>&nbsp;</span></p>
                                    <p>&nbsp;</p>
                                    <p id="infocollect"><span><strong>1. WHAT INFORMATION DO WE COLLECT?&nbsp;</strong>&nbsp;</span></p>
                                    <p><span><strong>Personal information you disclose to us</strong>&nbsp;</span></p>
                                    <p><span><strong><em>In Short:</em>&nbsp;</strong><em>We collect personal information that you provide to us such as name, address, contact information, passwords and security data,&nbsp;and payment information.</em></span></p>
                                    <p><span>We collect personal information that you voluntarily provide to us when&nbsp;registering at the&nbsp;Services&nbsp;expressing an interest in obtaining information about us or our products and services, when participating in activities on the&nbsp;Services&nbsp;(such as posting messages in our online forums or entering competitions, contests or giveaways)&nbsp;or otherwise contacting us.</span></p>
                                    <p><span>The personal information that we collect depends on the context of your interactions with us and the&nbsp;Services, the choices you make and the products and features you use. The personal information we collect can include the following:</span></p>
                                    <p><span><strong>Publicly Available Personal Information.</strong>&nbsp;We collect&nbsp;first name, maiden name, last name, nickname,&nbsp;social media,&nbsp;and other similar data.</span></p>
                                    <p><span><strong>Credentials.</strong>&nbsp;We collect passwords, password hints, and similar security information used for authentication and account access.&nbsp;&nbsp;</span></p>
                                    <p><span>All personal information that you provide to us must be true, complete and accurate, and you must notify us of any changes to such personal information.&nbsp;</span></p>
                                    <p><span><strong>Online Identifiers.</strong>&nbsp;We collect&nbsp;devices,&nbsp;and other similar data.&nbsp;&nbsp;&nbsp;</span><span></span><span></span></p>
                                    <p><span><strong>2. HOW DO WE USE YOUR INFORMATION?&nbsp;</strong>&nbsp;</span></p>
                                    <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>We process your information for purposes based on legitimate business interests, the fulfillment of our contract with you, compliance with our legal obligations, and/or your consent.</em>&nbsp;&nbsp;</span></p>
                                    <p><span>We use personal information collected via our&nbsp;Services&nbsp;for a variety of business purposes described below. We process your personal information for these purposes in reliance on our legitimate business interests, in order to enter into or perform a contract with you, with your consent, and/or for compliance with our legal obligations. We indicate the specific processing grounds we rely on next to each purpose listed below.&nbsp;</span></p>
                                    <p><span>&nbsp;</span></p>
                                    <p><span>We use the information we collect or receive:&nbsp;&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
                                    <ul>
                                        <li><span><strong>For other Business Purposes.</strong>&nbsp;We may use your information for other Business Purposes, such as data analysis, identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and improve our&nbsp;Services, products, marketing and your experience.&nbsp;We may use and store this information in aggregated and anonymized form so that it is not associated with individual end users and does not include personal information. We will not use identifiable personal information without your consent.</span><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></li>
                                    </ul>
                                    <p id="infoshare"><span><strong>3. WILL YOUR INFORMATION BE SHARED WITH ANYONE?&nbsp;</strong>&nbsp;</span></p>
                                    <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>We only share information with your consent, to comply with laws, to provide you with services, to protect your rights, or to fulfill business obligations.&nbsp;</em>&nbsp;&nbsp;</span></p>
                                    <div></div>
                                    <div><span>We may process or share data based on the following legal basis:</span></div>
                                    <ul>
                                        <li><span data-custom-class="body_text"><span data-custom-class="body_text"><strong>Consent:</strong>&nbsp;We may process your data if you have given us specific consent to use your personal information in a specific purpose.</span></span>&nbsp;</li>
                                        <li><span data-custom-class="body_text"><span data-custom-class="body_text"><strong>Legitimate Interests:</strong>&nbsp;We may process your data when it is reasonably necessary to achieve our legitimate business interests.</span></span>&nbsp;</li>
                                        <li><span data-custom-class="body_text"><span data-custom-class="body_text"><strong>Performance of a Contract:&nbsp;</strong>Where we have entered into a contract with you, we may process your personal information to fulfill the terms of our contract.</span></span>&nbsp;</li>
                                        <li><span data-custom-class="body_text"><span data-custom-class="body_text"><strong>Legal Obligations:</strong>&nbsp;We may disclose your information where we are legally required to do so in order to comply with applicable law, governmental requests, a judicial proceeding, court order, or legal process, such as in response to a court order or a subpoena (including in response to public authorities to meet national security or law enforcement requirements).</span></span>&nbsp;</li>
                                        <li><span><strong>Vital Interests:</strong>&nbsp;We may disclose your information where we believe it is necessary to investigate, prevent, or take action regarding potential violations of our policies, suspected fraud, situations involving potential threats to the safety of any person and illegal activities, or as evidence in litigation in which we are involved.</span></li>
                                    </ul>
                                    <p><span>More specifically, we may need to process your data or share your personal information in the following situations:&nbsp;</span><span>&nbsp;&nbsp;</span></p>
                                    <ul>
                                        <li><span><strong>Vendors, Consultants and Other Third-Party Service Providers.</strong>&nbsp;We may share your data with third party vendors, service providers, contractors or agents who perform services for us or on our behalf and require access to such information to do that work. Examples include: payment processing, data analysis, email delivery, hosting services, customer service and marketing efforts. We may allow selected third parties to use tracking technology on the&nbsp;Services, which will enable them to collect data about how you interact with the&nbsp;Services&nbsp;over time. This information may be used to, among other things, analyze and track data, determine the popularity of certain content and better understand online activity. Unless described in this Policy, we do not share, sell, rent or trade any of your information with third parties for their promotional purposes. &nbsp;&nbsp;</span>&nbsp;<span>&nbsp;</span></li>
                                        <li><span><strong>Business Transfers.</strong>&nbsp;We may share or transfer your information in connection with, or during negotiations of, any merger, sale of company assets, financing, or acquisition of all or a portion of our business to another company.&nbsp;</span></li>
                                        <li><span><strong>Third-Party Advertisers.</strong>&nbsp;We may use third-party advertising companies to serve ads when you visit the&nbsp;Services. These companies may use information about your visits to our Website(s) and other websites that are contained in web cookies and other tracking technologies in order to provide advertisements about goods and services of interest to you.&nbsp;&nbsp;</span>&nbsp;<span>&nbsp;</span>&nbsp;&nbsp;&nbsp;&nbsp;<span>&nbsp;</span>&nbsp;<span>&nbsp;</span><span data-custom-class="body_text"></span><span>&nbsp;&nbsp;&nbsp;</span></li>
                                    </ul>
                                </div>
                                <div></div>
                                <div><span id="cookies"><strong><span>4. DO WE USE COOKIES AND OTHER TRACKING TECHNOLOGIES?</span>&nbsp;</strong>&nbsp;</span></div>
                                <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>We may use cookies and other tracking technologies to collect and store your information.</em>&nbsp;&nbsp;</span></p>
                                <p><span>We may use cookies and similar tracking technologies (like web beacons and pixels) to access or store information. Specific information about how we use such technologies and how you can refuse certain cookies is set out in our Cookie Policy.</span></p>
                                <p><span>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
                                <p id="inforetain"><span><strong>5. HOW LONG DO WE KEEP YOUR INFORMATION?&nbsp;</strong>&nbsp;</span></p>
                                <p><span><strong><em>In Short:&nbsp;</em></strong><em>We keep your information for as long as necessary to fulfill the purposes outlined in this&nbsp;privacy policy&nbsp;unless otherwise required by law.&nbsp;</em>&nbsp;&nbsp;</span></p>
                                <p><span>We will only keep your personal information for as long as it is necessary for the purposes set out in this&nbsp;privacy policy, unless a longer retention period is required or permitted by law (such as tax, accounting or other legal requirements). No purpose in this policy will require us keeping your personal information for longer than&nbsp;90 days past the termination of the user’s account.&nbsp;&nbsp;</span></p>
                                <p><span>When we have no ongoing legitimate business need to process your personal information, we will either delete or anonymize it, or, if this is not possible (for example, because your personal information has been stored in backup archives), then we will securely store your personal information and isolate it from any further processing until deletion is possible.</span><span>&nbsp;&nbsp;&nbsp;</span></p>
                                <div></div>
                                <p id="infosafe"><span><strong>6. HOW DO WE KEEP YOUR INFORMATION SAFE?&nbsp;&nbsp;</strong>&nbsp;</span></p>
                                <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>We aim to protect your personal information through a system of organizational and technical security measures.</em>&nbsp;&nbsp;</span></p>
                                <p><span>We have implemented appropriate technical and organizational security measures designed to protect the security of any personal information we process. However, please also remember that we cannot guarantee that the internet itself is 100% secure. Although we will do our best to protect your personal information, transmission of personal information to and from our&nbsp;Services&nbsp;is at your own risk. You should only access the services within a secure environment.</span><span></span><span>&nbsp;&nbsp;</span></p>
                                <p id="infominors"><span><strong>7. DO WE COLLECT INFORMATION FROM MINORS?&nbsp;</strong>&nbsp;</span></p>
                                <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>We do not knowingly collect data from or market to children under 18 years of age.</em>&nbsp;&nbsp;</span></p>
                                <p><span>We do not knowingly solicit data from or market to children under 18 years of age. By using the&nbsp;Services, you represent that you are at least 18 or that you are the parent or guardian of such a minor and consent to such minor dependent’s use of the&nbsp;Services. If we learn that personal information from users less than 18 years of age has been collected, we will deactivate the account and take reasonable measures to promptly delete such data from our records. If you become aware of any data we have collected from children under age 18, please contact us at&nbsp;contact@surveybounce.com.&nbsp;&nbsp;</span></p>
                                <p id="privacyrights"><span><strong>8. WHAT ARE YOUR PRIVACY RIGHTS?&nbsp;</strong>&nbsp;</span></p>
                                <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>You may review, change, or terminate your account at any time.</em></span></p>
                                <p><span>If you are resident in the European Economic Area and you believe we are unlawfully processing your personal information, you also have the right to complain to your local data protection supervisory authority. You can find their contact details here:&nbsp;</span><span data-custom-class="body_text"><a data-custom-class="link" href="http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm" target="_blank" rel="noopener noreferrer">http://ec.europa.eu/justice/data-protection/bodies/authorities/index_en.htm</a>.&nbsp;</span><span><br>
</span></p>
                                <p><span><strong>Account Information</strong>&nbsp;&nbsp;</span></p>
                                <p><span>If you would at any time like to review or change the information in your account or terminate your account, you can:&nbsp;</span></p>
                                <p>■ &nbsp;<span>Contact us using the contact information provided.&nbsp;&nbsp;</span></p>
                                <p><span>Upon your request to terminate your account, we will deactivate or delete your account and information from our active databases. However, some information may be retained in our files to prevent fraud, troubleshoot problems, assist with any investigations, enforce our Terms of Use and/or comply with legal requirements.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
                                <p><span><strong><u>Cookies and similar technologies:</u>&nbsp;</strong>Most Web browsers are set to accept cookies by default. If you prefer, you can usually choose to set your browser to remove cookies and to reject cookies. If you choose to remove cookies or reject cookies, this could affect certain features or services of our&nbsp;Services. To opt-out of interest-based advertising by advertisers on our&nbsp;Services&nbsp;</span><span>&nbsp;visit&nbsp;</span><span data-custom-class="body_text"><a href="http://www.aboutads.info/choices/" target="_blank" rel="noopener noreferrer">http://www.aboutads.info/choices/</a></span><span>.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</span></p>
                                <p><span><strong><u>Opting out of email marketing:</u>&nbsp;</strong>You can unsubscribe from our marketing email list at any time by clicking on the unsubscribe link in the emails that we send or by contacting us using the details provided below. You will then be removed from the marketing email list – however, we will still need to send you service-related emails that are necessary for the administration and use of your account. To otherwise opt-out, you may:&nbsp;</span></p>
                                <div><span>&nbsp; &nbsp; ■ &nbsp;</span><span>Access your account settings and update preferences.</span></div>
                                <div></div>
                                <div></div>
                                <div></div>
                                <p id="DNT"><span><strong>9. CONTROLS FOR DO-NOT-TRACK FEATURES&nbsp;</strong>&nbsp;</span></p>
                                <p><span>Most web browsers and some mobile operating systems and mobile applications include a Do-Not-Track (“DNT”) feature or setting you can activate to signal your privacy preference not to have data about your online browsing activities monitored and collected. No uniform technology standard for recognizing and implementing DNT signals has been finalized. As such, we do not currently respond to DNT browser signals or any other mechanism that automatically communicates your choice not to be tracked online. If a standard for online tracking is adopted that we must follow in the future, we will inform you about that practice in a revised version of this&nbsp;privacy policy.&nbsp;&nbsp;</span></p>
                                <div></div>
                                <p id="caresidents"><span><strong>10. DO CALIFORNIA RESIDENTS HAVE SPECIFIC PRIVACY RIGHTS?&nbsp;</strong>&nbsp;</span></p>
                                <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>Yes, if you are a resident of California, you are granted specific rights regarding access to your personal information.&nbsp;</em>&nbsp;&nbsp;</span></p>
                                <p><span>California Civil Code Section 1798.83, also known as the “Shine The Light” law, permits our users who are California residents to request and obtain from us, once a year and free of charge, information about categories of personal information (if any) we disclosed to third parties for direct marketing purposes and the names and addresses of all third parties with which we shared personal information in the immediately preceding calendar year. If you are a California resident and would like to make such a request, please submit your request in writing to us using the contact information provided below.&nbsp;</span></p>
                                <p><span>If you are under 18 years of age, reside in California, and have a registered account with the&nbsp;Services, you have the right to request removal of unwanted data that you publicly post on the&nbsp;Services. To request removal of such data, please contact us using the contact information provided below, and include the email address associated with your account and a statement that you reside in California. We will make sure the data is not publicly displayed on the&nbsp;Services, but please be aware that the data may not be completely or comprehensively removed from our systems.</span></p>
                                <p id="policyupdates"><span><strong>11. DO WE MAKE UPDATES TO THIS POLICY?&nbsp;</strong>&nbsp;</span></p>
                                <p><span><strong><em>In Short:&nbsp;</em>&nbsp;</strong><em>Yes, we will update this policy as necessary to stay compliant with relevant laws.</em>&nbsp;&nbsp;</span></p>
                                <p><span>We may update this&nbsp;privacy policy&nbsp;from time to time. The updated version will be indicated by an updated “Revised” date and the updated version will be effective as soon as it is accessible. If we make material changes to this&nbsp;privacy policy, we may notify you either by prominently posting a notice of such changes or by directly sending you a notification. We encourage you to review this&nbsp;privacy policy&nbsp;frequently to be informed of how we are protecting your information.&nbsp;&nbsp;</span></p>
                                <p id="contact"><span><strong>12. HOW CAN YOU CONTACT US ABOUT THIS POLICY?&nbsp;</strong>&nbsp;</span></p>
                                <p><span>If you have questions or comments about this policy, you may&nbsp;email us at&nbsp;contact@surveybounce.com&nbsp;or by post to:</span></p>
                                <div><span>Survey Bounce&nbsp;&nbsp;&nbsp;&nbsp;</span></div>
                                <div><span data-custom-class="body_text">Laan van Langerhuize 1, Amstelveen, 1186 DS&nbsp;</span></div>
                                <div><span data-custom-class="body_text">__________&nbsp;</span><span data-custom-class="body_text">&nbsp;&nbsp;&nbsp;&nbsp;</span></div>
                                <div><span data-custom-class="body_text">Netherlands&nbsp;</span><span data-custom-class="body_text">&nbsp;</span><span>&nbsp;</span></div>
                                <div></div>
                                <div></div>
                                <div>
                                    <h1>HOW CAN YOU REVIEW, UPDATE, OR DELETE THE DATA WE COLLECT FROM YOU?</h1>
                                    <div>Based on the laws of some countries, you may have the right to request access to the personal information we collect from you, change that information, or delete it in some circumstances. To request to review, update, or delete your personal information, please submit a request form by clicking<span>&nbsp;</span><a href="/contact-us/">here</a>. We will respond to your request within 30 days.</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="document-preview-layout-style-wrapper-279869">
                        <div class="document-preview-layout-custom-branding-wrapper-28b4e8"></div>
                        <div class="document-preview-layout-wrapper-upgrade-prompt-custom-style-31d1f1">
                            <div class="upgrade-prompt-container-9ed296">
                                <div class="upgrade-prompt-message-c1c7ce"></div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>

    </main>


@endsection
@section('jscript')
    <script type="text/javascript">
    </script>
@endsection
